// for models
const mongoose = require('mongoose');

// creating a UserSchema
const NotesSchema = new mongoose.Schema({
    // For linking notes and user
    user: {
        // type of user data will be id generated by Mongoose in DB
        type: mongoose.Schema.Types.ObjectId,
        // reference is user model
        ref:'user'
    },
    title: {
        type: String,
        required: true,
    },
    description:{
        type: String,
        required: true,
    },
    tag:{
        type: String,
        default: "General"
    },
    date:{
        type: Date,
        default: Date.now
    }
})

// mongoose.model will make a new model, ("model_name", "Schema")
module.exports = mongoose.model('notes',NotesSchema);